### ISSUE TITLE
2020_07_16_RAID

### ISSUE THREAD

**Issue by lucexa** [dannyroemhild/fisi-ausbildungsinhalte#5]
**RAID (Redundant Array of Independent Disks)** sollte ausführlich im Fach IT-Systeme Hinzugefügt werden.

Folgende Raid Level sollten in diesem Lernfeld näher gebracht werden:

- RAID 0 
- RAID 1
- RAID 3
- RAID 5
- RAID 6
- RAID 0+1
- RAID 1+0

Diese RAID Level werden derzeit im Rahmen der Therotischen Ausbildung vermittelt und sollten im Praktischen Umfeld verstanden werden.

Zudem sollte **JBOD** in diesem Lernfeld aufgeführt werden.

**Comment by dannyroemhild** [comment]
Solved with #9cfd89f0caa93e53dde85ce875fb0154938b3613
